import { readFile, writeFile, readdir } from 'node:fs/promises';
import { tools } from '../src/data/tools.js';

const root = new URL('../', import.meta.url);
const esc = value => value.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const decode = value => {
  let result = value;
  while (/&(?:amp|quot|lt|gt);/i.test(result)) result = result.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&lt;','<').replaceAll('&gt;','>');
  return result;
};
const head = ({title,description,path='',depth='.',type='website'}) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://reflextester.vercel.app/${path}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="https://reflextester.vercel.app/${path}"><link rel="icon" href="${depth}/favicon.ico"><link rel="stylesheet" href="${depth}/src/styles/base.css">`;
const end = module => `<script type="module" src="${module}"></script></body></html>`;

for (const tool of tools) {
  const html = `${head({title:`${tool.name} — ReflexTester`,description:tool.description,path:`tools/${tool.slug}.html`,depth:'..'})}<link rel="stylesheet" href="../src/styles/tool.css"></head><body data-tool="${tool.slug}"><main id="main"></main>${end('../src/app/tool-page.js')}`;
  await writeFile(new URL(`../tools/${tool.slug}.html`,import.meta.url),html);
}

const rootPages = {
  'index.html': `${head({title:'ReflexTester — Reaction, aim and cognitive performance tools',description:'Measure reaction speed, train mouse control and use precise game utilities in your browser.'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"></main>${end('./src/app/home.js')}`,
  'tools.html': `${head({title:'Tests, training and game utilities — ReflexTester',description:'Browse reaction tests, aim training, cognitive exercises and game setup utilities.',path:'tools.html'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"></main>${end('./src/app/catalog.js')}`,
  'dashboard.html': `${head({title:'Your local results — ReflexTester',description:'Review real attempts, personal bests and averages stored in this browser.',path:'dashboard.html'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"></main>${end('./src/app/dashboard.js')}`,
  'about.html': `${head({title:'About ReflexTester',description:'How ReflexTester approaches browser-based performance measurement and practice.',path:'about.html'})}<link rel="stylesheet" href="./src/styles/article.css"></head><body><main id="main" class="article-layout"><article class="article"><span class="eyebrow">About</span><h1>Performance tools with clear limits.</h1><p>ReflexTester provides browser-based tests, practice drills and game configuration utilities. It works without an account and stores personal results locally.</p><h2>What the measurements mean</h2><p>A browser result includes human response time plus display, operating-system and input-device latency. The tools are designed for personal comparison under consistent conditions; they are not medical or diagnostic instruments.</p><h2>How the product is built</h2><p>Timing-sensitive tests use monotonic browser timing, interactive drills use Pointer Events, and statistics come only from completed activity on the current device.</p></article></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`,
  'contact.html': `${head({title:'Contact ReflexTester',description:'Contact the ReflexTester team.',path:'contact.html'})}<link rel="stylesheet" href="./src/styles/article.css"></head><body><main id="main" class="article-layout"><article class="article"><span class="eyebrow">Contact</span><h1>Report a problem or suggest an improvement.</h1><p>Include the tool name, browser, device type and the steps that produced the issue.</p><p><a class="button accent" href="mailto:contact@reflextester.fun">contact@reflextester.fun</a></p></article></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`,
  'privacy-policy.html': `${head({title:'Privacy policy — ReflexTester',description:'How ReflexTester handles local results, analytics and affiliate links.',path:'privacy-policy.html'})}<link rel="stylesheet" href="./src/styles/article.css"></head><body><main id="main" class="article-layout"><article class="article"><span class="eyebrow">Legal</span><h1>Privacy policy</h1><p>Last updated 21 September 2026.</p><h2>Local activity data</h2><p>Test results and preferences are stored in your browser using local storage. They are not an account and are not transmitted by the result system. You can clear them from the Results page.</p><h2>Analytics and hosting</h2><p>Hosting providers may process standard request information such as IP address, browser information and requested URL for delivery and security. If analytics are enabled, they may collect aggregate usage information.</p><h2>Affiliate links</h2><p>Some guides contain clearly disclosed Amazon affiliate links. Clicking them can allow Amazon to associate a qualifying purchase with this website.</p><h2>Contact</h2><p>Questions can be sent to <a href="mailto:contact@reflextester.fun">contact@reflextester.fun</a>.</p></article></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`,
  'terms-of-service.html': `${head({title:'Terms of service — ReflexTester',description:'Terms for using ReflexTester browser tools and written content.',path:'terms-of-service.html'})}<link rel="stylesheet" href="./src/styles/article.css"></head><body><main id="main" class="article-layout"><article class="article"><span class="eyebrow">Legal</span><h1>Terms of service</h1><p>Last updated 21 September 2026.</p><h2>Use of the tools</h2><p>ReflexTester is provided for general information, recreation and personal practice. Results are affected by hardware and software conditions and must not be treated as medical, occupational or safety certification.</p><h2>Content and third parties</h2><p>Game names and trademarks belong to their respective owners. Links to third-party websites are governed by those websites' terms.</p><h2>Availability</h2><p>Tools may change as browsers and platform requirements evolve. We do not guarantee uninterrupted availability.</p></article></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`,
  '404.html': `${head({title:'Page not found — ReflexTester',description:'The requested ReflexTester page could not be found.',path:'404.html'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"><div class="page"><span class="eyebrow">404</span><h1>That page is not here.</h1><p class="lede">The URL may have changed or been entered incorrectly.</p><a class="button accent" href="./tools.html">Browse tools</a></div></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`,
  '500.html': `${head({title:'Something went wrong — ReflexTester',description:'ReflexTester encountered an unexpected error.',path:'500.html'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"><div class="page"><span class="eyebrow">Error</span><h1>Something went wrong.</h1><p class="lede">Reload the page. If the problem continues, report the tool and browser you were using.</p><a class="button accent" href="./index.html">Return home</a></div></main><script type="module">import{mountShell}from'./src/app/shell.js';mountShell()</script></body></html>`
};
for (const [file,html] of Object.entries(rootPages)) await writeFile(new URL(`../${file}`,import.meta.url),html);

const blogFiles=(await readdir(new URL('../blog/',import.meta.url))).filter(file=>file.endsWith('.html')&&file!=='index.html');
const articles=[];
for(const file of blogFiles){
  const source=await readFile(new URL(`../blog/${file}`,import.meta.url),'utf8');
  const title=decode(source.match(/<title>(.*?)<\/title>/is)?.[1]||file.replace('.html','').replaceAll('-',' ')).replace(/\s*(?:\||—)\s*ReflexTester.*$/i,'').replaceAll('TimeA Complete','Time: Complete').replaceAll('TimesA','Times:').trim();
  const description=source.match(/<meta\s+name="description"\s+content="([^"]*)"/i)?.[1]||`Read ${title} on ReflexTester.`;
  const startCandidates=[source.indexOf('<article class="blog-article"'),source.indexOf('<article class="affiliate-article"'),source.indexOf('<article class="article"'),source.indexOf('<article>')].filter(index=>index>=0);
  if(!startCandidates.length) continue;
  const start=Math.min(...startCandidates),endIndex=source.indexOf('</article>',start);
  let article=source.slice(start,endIndex+10)
    .replace(/<script[\s\S]*?<\/script>/gi,'')
    .replace(/<img\b[^>]*>/gi,'')
    .replaceAll('TimeA Complete','Time: Complete')
    .replaceAll('TimesA','Times:');
  article=article.replace(/class="blog-article"/,'class="article"').replace(/class="affiliate-article"/,'class="article"').replace(/<div class="affiliate-body">/,'<div>');
  article=article.replace(/\s+id="section-\d+"/gi,'');
  const headings=[...article.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/gi)].map((match,index)=>({id:`section-${index+1}`,label:match[1].replace(/<[^>]+>/g,'').trim()}));
  let headingIndex=0;article=article.replace(/<h2([^>]*)>/gi,(_,attrs)=>`<h2${attrs} id="${headings[headingIndex++]?.id||''}">`);
  const toc=headings.length>2?`<aside class="article-aside"><span class="eyebrow">On this page</span><nav>${headings.map(h=>`<a href="#${h.id}">${h.label}</a>`).join('')}</nav></aside>`:'';
  const html=`${head({title:`${title} — ReflexTester`,description,path:`blog/${file}`,depth:'..',type:'article'})}<link rel="stylesheet" href="../src/styles/article.css"></head><body><main id="main" class="article-layout">${article}${toc}</main><script type="module">import {mountShell} from '../src/app/shell.js';mountShell('learn')</script></body></html>`;
  await writeFile(new URL(`../blog/${file}`,import.meta.url),html.replace(/[ \t]+$/gm,''));
  articles.push({file,title,description});
}

const cards=articles.map(article=>`<a class="tool-row" href="./blog/${article.file}"><span class="tool-kind">Guide</span><span class="tool-name">${article.title}</span><p>${article.description}</p><span class="tool-arrow">→</span></a>`).join('');
const blogIndex=`${head({title:'Guides — ReflexTester',description:'Practical guides to reaction time, aim training, cognition and performance.',path:'blog.html'})}<link rel="stylesheet" href="./src/styles/site.css"></head><body><main id="main"><div class="page"><header class="catalog-head"><div><span class="eyebrow">Learning</span><h1>Understand your performance.</h1><p class="lede">Evidence-aware explanations and practical training guidance.</p></div><label class="field"><span>Search guides</span><input type="search" data-search placeholder="Reaction time, sleep, hardware…"></label></header><div class="tool-list" data-list>${cards}</div></div></main><script type="module">import {mountShell} from './src/app/shell.js';mountShell('learn');const input=document.querySelector('[data-search]');input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('.tool-row').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}</script></body></html>`;
await writeFile(new URL('../blog.html',import.meta.url),blogIndex);
const insideCards=articles.map(article=>`<a class="tool-row" href="./${article.file}"><span class="tool-kind">Guide</span><span class="tool-name">${article.title}</span><p>${article.description}</p><span class="tool-arrow">→</span></a>`).join('');
const insideIndex=`${head({title:'Guides — ReflexTester',description:'Practical guides to reaction time, aim training, cognition and performance.',path:'blog/',depth:'..'})}<link rel="stylesheet" href="../src/styles/site.css"></head><body><main id="main"><div class="page"><header class="catalog-head"><div><span class="eyebrow">Learning</span><h1>Understand your performance.</h1><p class="lede">Evidence-aware explanations and practical training guidance.</p></div><label class="field"><span>Search guides</span><input type="search" data-search placeholder="Reaction time, sleep, hardware…"></label></header><div class="tool-list" data-list>${insideCards}</div></div></main><script type="module">import {mountShell} from '../src/app/shell.js';mountShell('learn');const input=document.querySelector('[data-search]');input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('.tool-row').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}</script></body></html>`;
await writeFile(new URL('../blog/index.html',import.meta.url),insideIndex);

console.log(`Generated ${tools.length} tool routes and migrated ${articles.length} articles.`);
