import { store } from '../core/store.js';

export function mountAim(root, tool) {
  let score=0, shots=0, hits=0, running=false, endAt=0, raf=0, last=performance.now();
  root.innerHTML=`<div class="target-stage"><div class="instruction" data-intro><span class="eyebrow">${tool.category} drill</span><h2>${tool.name}</h2><p>${tool.description} The session runs for 30 seconds.</p><button class="button accent">Start session</button></div><div class="aim-hud" hidden><span><strong data-time>30.0</strong>s</span><span><strong data-score>0</strong> hits</span><span><strong data-accuracy>100</strong>% accuracy</span></div></div>`;
  const stage=root.firstElementChild,intro=stage.querySelector('[data-intro]'),hud=stage.querySelector('.aim-hud');
  function place(target){const rect=stage.getBoundingClientRect();const pad=50;target.style.left=`${pad+Math.random()*Math.max(1,rect.width-pad*2)}px`;const headLevel=['valorant','cs2'].includes(tool.mechanic);target.style.top=headLevel?`${Math.max(70,rect.height*.34+Math.random()*50)}px`:`${pad+Math.random()*Math.max(1,rect.height-pad*2)}px`;}
  function spawn(){stage.querySelectorAll('.aim-target,.tracking-target').forEach(node=>node.remove());const target=document.createElement('button');target.setAttribute('aria-label','Target');target.className=['tracking','apex'].includes(tool.mechanic)?'tracking-target':'aim-target';if(['precision','valorant','cs2'].includes(tool.mechanic))target.classList.add('small');if(tool.mechanic==='spider'&&hits%2===1)target.classList.add('center');if(tool.mechanic==='fortnite'){target.style.width='5rem';target.style.height='5rem'}place(target);stage.append(target);target.addEventListener('pointerdown',event=>{event.stopPropagation();if(!running)return;shots++;hits++;score++;stage.querySelector('[data-score]').textContent=hits;stage.querySelector('[data-accuracy]').textContent=Math.round(hits/shots*100);target.remove();spawn();});}
  function finish(){running=false;cancelAnimationFrame(raf);stage.querySelectorAll('.aim-target,.tracking-target').forEach(n=>n.remove());const accuracy=shots?hits/shots*100:100;store.record(tool.slug,{score:hits,accuracy,shots,unit:'hits'});stage.innerHTML=`<div class="result-panel"><span class="eyebrow">Session complete</span><div class="instrument-readout">${hits}<span class="instrument-unit">hits</span></div><div class="result-detail"><div><strong>${accuracy.toFixed(0)}%</strong><span>Accuracy</span></div><div><strong>${shots}</strong><span>Inputs</span></div><div><strong>30s</strong><span>Duration</span></div></div><button class="button accent" data-retry>Run again</button></div>`;stage.querySelector('[data-retry]').onclick=()=>mountAim(root,tool);}
  function frame(now){if(!running)return;const remain=(endAt-now)/1000;if(remain<=0)return finish();stage.querySelector('[data-time]').textContent=remain.toFixed(1);const target=stage.querySelector('.tracking-target');if(target){const rect=stage.getBoundingClientRect();let x=parseFloat(target.style.left),y=parseFloat(target.style.top);const speed=tool.mechanic==='apex'?3.1:2.2;x+=Math.cos(now/530)*speed;y+=Math.sin(now/410)*speed*.78;target.style.left=`${Math.max(35,Math.min(rect.width-35,x))}px`;target.style.top=`${Math.max(35,Math.min(rect.height-35,y))}px`;}last=now;raf=requestAnimationFrame(frame);}
  stage.addEventListener('pointerdown',()=>{if(running){shots++;stage.querySelector('[data-accuracy]').textContent=Math.round(hits/shots*100);}});
  intro.querySelector('button').onclick=()=>{running=true;endAt=performance.now()+30000;intro.remove();hud.hidden=false;hud.style.position='absolute';hud.style.zIndex='2';hud.style.top='1rem';hud.style.left='1rem';spawn();raf=requestAnimationFrame(frame);};
}
